bot:
  general:
    name: group_eq_bot
    version: 1.0
    token:
    link: t.me/GroupEQBot
  validation:
    # now we support 10 questions overall
    # this parameter is controlled in question schema (index_number)
    questions:
        [
          {location_type: 'local', question_type: 'text', index_number: 2, question: None, question_path: '${hydra:runtime.cwd}/assets/text/first_question.txt', answer: 'Good, let"s move forwards.', attempts_to_fail: 2},
          {location_type: 'local', question_type: 'text', index_number: 3, question: 'What"s your occupation ?', question_path: None, answer: 'Awesome, are you looking for a job now ?', attempts_to_fail: 2},
          {location_type: 'local', question_type: 'audio', index_number: 1, question: None, question_path: '${hydra:runtime.cwd}/assets/audio/first_question.m4a', answer: 'bla bla bla', attempts_to_fail: 3},
        ]
    welcome_message: 'You have to pass the validation here: ${bot.general.link}'
    remaining_attemps_message: |-
            I got unexpected answer -_- Please listen to the question one more time!

                          Left attempts for this question:
    validation_failed_message: |-
            I got too many unexpected answers and there are no more attempts.

            Verification failed and you will not get the access to the group O_O.
    validation_canceled_message: " To try again type '/start_validation'. "
    validation_passed_message: " Congratulations, you passed the validation. Welcome! "
    stop_validation_for_owner: 'You are the owner! No need to validate yourself ^_^ '

events_database:
  infrastructure:
    number_of_shards: 2
    number_of_replicas: 0
  indices:
    index_template: ${bot.general.name}-${bot.general.version}
  available_hosts:
    localhost: 127.0.0.1
    container: host.docker.internal
  which_host_to_use:
    host: ${events_database.available_hosts.container}  # is used in source.group_eq_bot.storage.events_driven_database.connectors.connector


